# Generated by Django 5.2.9 on 2026-03-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authorization',
            field=models.CharField(choices=[('1', 'Yönetici'), ('2', 'Admin'), ('3', 'Kullanıcı')], default='2', max_length=11, verbose_name='Yetki'),
        ),
    ]
