# Generated by Django 6.0 on 2026-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_model', models.CharField(max_length=100, verbose_name='Pompa Modeli')),
                ('kademe', models.PositiveIntegerField(verbose_name='Kademe')),
                ('power_kw', models.FloatField(verbose_name='Güç (kW)')),
                ('q_values_lps', models.JSONField(verbose_name='Q Listesi (L/s)')),
                ('h_values', models.JSONField(verbose_name='H Listesi (m)')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('passive', 'Pasif')], default='active', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pompa Kataloğu',
                'verbose_name_plural': 'Pompa Kataloğu',
                'ordering': ['pump_model', 'kademe'],
                'constraints': [models.UniqueConstraint(fields=('pump_model', 'kademe'), name='unique_pump_model_kademe')],
            },
        ),
    ]
