# Generated by Django 6.0 on 2026-05-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_pumpcatalog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pumpcatalog',
            name='unique_pump_model_kademe',
        ),
        migrations.DeleteModel(
            name='PumpCatalog',
        ),
    ]
