# Generated by Django 5.2.9 on 2026-02-23 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='CategoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='Malzeme Adı')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miktar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='other_materials.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategori Stok',
                'verbose_name_plural': 'Kategori Stokları',
                'unique_together': {('category', 'material_name')},
            },
        ),
    ]
