# Generated by Django 5.2.9 on 2026-02-23 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_materials', '0001_initial'),
        ('warehouses', '0049_order_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorystock',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='CategoryStockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Çıkış Miktarı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='warehouses.order', verbose_name='Sipariş')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outs', to='other_materials.categorystock', verbose_name='Kategori Stok')),
            ],
            options={
                'verbose_name': 'Kategori Stok Çıkışı',
                'verbose_name_plural': 'Kategori Stok Çıkışları',
            },
        ),
    ]
