# Generated by Django 5.2.9 on 2026-02-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_materials', '0002_alter_categorystock_unique_together_categorystockout'),
        ('warehouses', '0050_workshopexitslip_modal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystockout',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='warehouses.order', verbose_name='Sipariş'),
        ),
        migrations.AlterField(
            model_name='categorystockout',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outs', to='other_materials.categorystock', verbose_name='Kategori Stok'),
        ),
    ]
