# Generated by Django 5.2.9 on 2026-03-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_materials', '0003_alter_categorystockout_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorystockout',
            options={'ordering': ['created_at'], 'verbose_name': 'Kategori Stok Çıkışı', 'verbose_name_plural': 'Kategori Stok Çıkışları'},
        ),
        migrations.RemoveField(
            model_name='categorystockout',
            name='order',
        ),
        migrations.AddField(
            model_name='categorystockout',
            name='address',
            field=models.CharField(default=1, max_length=50, verbose_name='Adres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorystockout',
            name='district',
            field=models.CharField(choices=[('akçakale', 'AKÇAKALE'), ('eyyübiye', 'EYYÜBİYE'), ('birecik', 'BİRECİK'), ('bozova', 'BOZOVA'), ('ceylanpınar', 'CEYLANPINAR'), ('halfeti', 'HALFETİ'), ('haliliye', 'HALİLİYE'), ('harran', 'HARRAN'), ('hilvan', 'HİLVAN'), ('karaköprü', 'KARAKÖPRÜ'), ('siverek', 'SİVEREK'), ('suruç', 'SURUÇ'), ('viranşehir', 'VİRANŞEHİR')], default=1, max_length=50, verbose_name='İlçe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorystockout',
            name='well_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kuyu Numarası'),
        ),
    ]
