# Generated by Django 5.2.9 on 2026-03-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_materials', '0004_alter_categorystockout_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorystockout',
            name='outlet_plug',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Çıkış Fişi'),
        ),
    ]
