# Generated by Django 6.0 on 2026-04-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_materials', '0005_categorystockout_outlet_plug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystockout',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
