# Generated by Django 5.2.9 on 2026-01-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hydrophore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(verbose_name='Hidrofor Seri Numarası')),
                ('engine_power', models.FloatField(verbose_name='Motor Gücü')),
                ('engine_brand', models.CharField(max_length=100, verbose_name='Motor Markası')),
                ('pump_type', models.CharField(max_length=100, verbose_name='Pompa Tipi')),
                ('pump_brand', models.CharField(max_length=100, verbose_name='Pompa Markası')),
                ('location', models.CharField(choices=[('Ankara', 'Ankara'), ('Istanbul', 'İstanbul'), ('Izmir', 'İzmir'), ('Bursa', 'Bursa')], max_length=50, verbose_name='Lokasyon')),
                ('neighborhood', models.CharField(blank=True, choices=[('Neighborhood 1', 'Mahalle 1'), ('Neighborhood 2', 'Mahalle 2'), ('Neighborhood 3', 'Mahalle 3')], max_length=100, null=True, verbose_name='Mahalle')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
            ],
            options={
                'verbose_name': 'Hidrofor',
                'verbose_name_plural': 'Hidroforlar',
            },
        ),
    ]
