# Generated by Django 5.2.9 on 2026-01-10 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField(unique=True, verbose_name='Güç')),
            ],
        ),
        migrations.CreateModel(
            name='PumpType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='Pompa Tipi')),
            ],
        ),
        migrations.RemoveField(
            model_name='hydrophore',
            name='pump_brand',
        ),
        migrations.AlterField(
            model_name='hydrophore',
            name='district',
            field=models.CharField(blank=True, choices=[('akçakale', 'AKÇAKALE'), ('eyyübiye', 'EYYÜBİYE'), ('birecik', 'BİRECİK'), ('bozova', 'BOZOVA'), ('ceylanpınar', 'CEYLANPINAR'), ('halfeti', 'HALFETİ'), ('haliliye', 'HALİLİYE'), ('harran', 'HARRAN'), ('hilvan', 'HİLVAN'), ('karaköprü', 'KARAKÖPRÜ'), ('siverek', 'SİVEREK'), ('suruç', 'SURUÇ'), ('viranşehir', 'VİRANŞEHİR')], max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='hydrophore',
            name='location',
            field=models.CharField(blank='1', choices=[('1', 'Atölyede'), ('2', 'Atölyede Tamir Bekliyor'), ('3', 'Elektrikçide'), ('4', 'Kuyuda'), ('5', 'Tamirde'), ('6', 'Sıfır Depo'), ('7', 'Pert Depo')], max_length=50, verbose_name='Lokasyon'),
        ),
        migrations.AlterField(
            model_name='hydrophore',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahalle'),
        ),
        migrations.AlterField(
            model_name='hydrophore',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Hidrofor Seri Numarası'),
        ),
        migrations.AlterField(
            model_name='hydrophore',
            name='engine_power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hydrophore.power', verbose_name='Motor Gücü'),
        ),
        migrations.AlterField(
            model_name='hydrophore',
            name='pump_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hydrophore.pumptype', verbose_name='Pompa Tipi'),
        ),
    ]
