# Generated by Django 5.2.9 on 2026-01-10 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0002_power_pumptype_remove_hydrophore_pump_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrophore',
            name='location',
            field=models.CharField(choices=[('1', 'Atölyede'), ('2', 'Atölyede Tamir Bekliyor'), ('3', 'Elektrikçide'), ('4', 'Kuyuda'), ('5', 'Tamirde'), ('6', 'Sıfır Depo'), ('7', 'Pert Depo')], default='1', max_length=50, verbose_name='Lokasyon'),
        ),
        migrations.CreateModel(
            name='OutboundWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('akçakale', 'AKÇAKALE'), ('eyyübiye', 'EYYÜBİYE'), ('birecik', 'BİRECİK'), ('bozova', 'BOZOVA'), ('ceylanpınar', 'CEYLANPINAR'), ('halfeti', 'HALFETİ'), ('haliliye', 'HALİLİYE'), ('harran', 'HARRAN'), ('hilvan', 'HİLVAN'), ('karaköprü', 'KARAKÖPRÜ'), ('siverek', 'SİVEREK'), ('suruç', 'SURUÇ'), ('viranşehir', 'VİRANŞEHİR')], max_length=100, verbose_name='İlçe')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Mahalle')),
                ('dispatch_slip_number', models.CharField(max_length=100, verbose_name='Çıkış Fişi No')),
                ('dispatch_date', models.DateField(verbose_name='Çıkış Fişi Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('passive', 'Pasif')], default='active', max_length=10, verbose_name='Durum')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('hydrophore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_work_orders', to='hydrophore.hydrophore', verbose_name='Hidrofor')),
            ],
            options={
                'verbose_name': 'Çıkış İş Emri',
                'verbose_name_plural': 'Çıkış İş Emirleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
