# Generated by Django 5.2.9 on 2026-01-11 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0003_alter_hydrophore_location_outboundworkorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'verbose_name': 'Güç', 'verbose_name_plural': 'Güçler'},
        ),
        migrations.AlterModelOptions(
            name='pumptype',
            options={'verbose_name': 'Pompa Tipi', 'verbose_name_plural': 'Pompa Tipleri'},
        ),
        migrations.CreateModel(
            name='WorkshopExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_dispatch_slip_number', models.CharField(max_length=100, verbose_name='Atölyeden Giden Fiş No')),
                ('workshop_dispatch_date', models.DateField(verbose_name='Fiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('passive', 'Pasif')], default='active', max_length=10, verbose_name='Durum')),
                ('hydrophore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_exits', to='hydrophore.hydrophore', verbose_name='Hidrofor')),
                ('outbound_work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_exits', to='hydrophore.outboundworkorder', verbose_name='Çıkış İş Emri')),
            ],
            options={
                'verbose_name': 'Atölye Çıkışı',
                'verbose_name_plural': 'Atölye Çıkışları',
                'ordering': ['-workshop_dispatch_date'],
            },
        ),
        migrations.CreateModel(
            name='RepairReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_return_slip_number', models.CharField(max_length=100, verbose_name='Tamirden Gelen Fiş No')),
                ('repair_return_date', models.DateField(verbose_name='Fiş Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('passive', 'Pasif')], default='active', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('hydrophore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_returns', to='hydrophore.hydrophore', verbose_name='Hidrofor')),
                ('workshop_exit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_returns', to='hydrophore.workshopexit', verbose_name='Atölye Çıkışı')),
            ],
            options={
                'verbose_name': 'Tamirden Geri Geliş',
                'verbose_name_plural': 'Tamirden Geri Gelişler',
                'ordering': ['-repair_return_date'],
            },
        ),
    ]
