# Generated by Django 5.2.9 on 2026-01-11 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0004_alter_power_options_alter_pumptype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundworkorder',
            name='hydrophore',
        ),
        migrations.AddField(
            model_name='outboundworkorder',
            name='disassembled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Çıkış Fişi Tarihi'),
        ),
        migrations.AddField(
            model_name='outboundworkorder',
            name='disassembled_hydrophore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='disassembled_work_orders', to='hydrophore.hydrophore', verbose_name='Sökülen Hidrofor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundworkorder',
            name='mounted_hydrophore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mounted_work_orders', to='hydrophore.hydrophore', verbose_name='Takılan Hidrofor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outboundworkorder',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True, verbose_name='Çıkış Fişi Tarihi'),
        ),
    ]
