# Generated by Django 5.2.9 on 2026-01-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0005_remove_outboundworkorder_hydrophore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundworkorder',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
