# Generated by Django 5.2.9 on 2026-01-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0006_outboundworkorder_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundworkorder',
            name='disassembled_date',
            field=models.DateField(blank=True, null=True, verbose_name=' Demontaj Hidrofor Geldiği Tarih'),
        ),
        migrations.AlterField(
            model_name='outboundworkorder',
            name='disassembled_hydrophore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disassembled_work_orders', to='hydrophore.hydrophore', verbose_name='Sökülen Hidrofor'),
        ),
    ]
