# Generated by Django 5.2.9 on 2026-01-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0007_alter_outboundworkorder_disassembled_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictFieldPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Adı Soyadı')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon')),
                ('district', models.CharField(choices=[('akçakale', 'AKÇAKALE'), ('eyyübiye', 'EYYÜBİYE'), ('birecik', 'BİRECİK'), ('bozova', 'BOZOVA'), ('ceylanpınar', 'CEYLANPINAR'), ('halfeti', 'HALFETİ'), ('haliliye', 'HALİLİYE'), ('harran', 'HARRAN'), ('hilvan', 'HİLVAN'), ('karaköprü', 'KARAKÖPRÜ'), ('siverek', 'SİVEREK'), ('suruç', 'SURUÇ'), ('viranşehir', 'VİRANŞEHİR')], max_length=100, verbose_name='İlçe')),
                ('vehicle_plate', models.CharField(max_length=15, verbose_name='Plaka')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'İlçe Saha Personeli',
                'verbose_name_plural': 'İlçe Saha Personelleri',
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterField(
            model_name='outboundworkorder',
            name='dispatch_date',
            field=models.DateField(verbose_name='Çıkış Fişi Tarihi'),
        ),
    ]
