# Generated by Django 5.2.9 on 2026-01-11 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0008_districtfieldpersonnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundworkorder',
            name='district_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydrophore.districtfieldpersonnel', verbose_name='Saha Personeli'),
        ),
        migrations.AlterField(
            model_name='outboundworkorder',
            name='disassembled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Demontaj Hidrofor Geldiği Tarih'),
        ),
    ]
