# Generated by Django 5.2.9 on 2026-01-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0009_outboundworkorder_district_personnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundworkorder',
            name='district_personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hydrophore.districtfieldpersonnel', verbose_name='Saha Personeli'),
        ),
    ]
