# Generated by Django 6.0 on 2026-01-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0010_alter_outboundworkorder_district_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopexit',
            name='workshop_dispatch_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='workshopexit',
            name='workshop_dispatch_slip_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atölyeden Giden Fiş No'),
        ),
    ]
