# Generated by Django 5.2.9 on 2026-02-10 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0013_alter_repairreturn_repair_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundworkorder',
            name='dispatch_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Çıkış Fişi Tarihi'),
        ),
    ]
