# Generated by Django 5.2.9 on 2026-02-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0014_alter_outboundworkorder_dispatch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopexit',
            name='outbound_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_exits', to='hydrophore.outboundworkorder', verbose_name='Çıkış İş Emri'),
        ),
    ]
