# Generated by Django 5.2.9 on 2026-02-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0015_alter_workshopexit_outbound_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundworkorder',
            name='dispatch_slip_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Çıkış Fişi No'),
        ),
    ]
