# Generated by Django 5.2.9 on 2026-02-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0016_alter_outboundworkorder_dispatch_slip_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'ordering': ['power'], 'verbose_name': 'Güç', 'verbose_name_plural': 'Güçler'},
        ),
        migrations.AlterModelOptions(
            name='pumptype',
            options={'ordering': ['type'], 'verbose_name': 'Pompa Tipi', 'verbose_name_plural': 'Pompa Tipleri'},
        ),
    ]
