# Generated by Django 5.2.9 on 2026-03-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0017_alter_power_options_alter_pumptype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopexit',
            name='district',
            field=models.CharField(blank=True, choices=[('akçakale', 'AKÇAKALE'), ('eyyübiye', 'EYYÜBİYE'), ('birecik', 'BİRECİK'), ('bozova', 'BOZOVA'), ('ceylanpınar', 'CEYLANPINAR'), ('halfeti', 'HALFETİ'), ('haliliye', 'HALİLİYE'), ('harran', 'HARRAN'), ('hilvan', 'HİLVAN'), ('karaköprü', 'KARAKÖPRÜ'), ('siverek', 'SİVEREK'), ('suruç', 'SURUÇ'), ('viranşehir', 'VİRANŞEHİR')], max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='workshopexit',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahalle'),
        ),
    ]
