# Generated by Django 5.2.9 on 2026-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0018_workshopexit_district_workshopexit_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopexit',
            name='workshop_dispatch_slip_number',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Atölyeden Giden Fiş No'),
            preserve_default=False,
        ),
    ]
