# Generated by Django 5.2.9 on 2026-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrophore', '0021_alter_workshopexit_workshop_dispatch_slip_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopexit',
            name='workshop_dispatch_slip_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atölyeden Giden Fiş No'),
        ),
    ]
