# Generated by Django 5.2.9 on 2025-12-08 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_mark', models.CharField(max_length=50, unique=True, verbose_name='Marka')),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_power', models.FloatField(unique=True, verbose_name='Motor Gücü')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(choices=[('1', '3"'), ('2', '4"'), ('3', '5"'), ('4', '6"'), ('5', '7"'), ('6', '8"'), ('7', '9"'), ('8', '10"'), ('9', '11"'), ('10', 'ASENKRON'), ('11', '-')], max_length=4, verbose_name='Motor Tipi')),
                ('serialnumber', models.CharField(max_length=100, unique=True, verbose_name='Seri Numarası')),
                ('location', models.CharField(choices=[('1', 'Kuyuda'), ('2', 'Tamir Depo'), ('3', '2.El Depo'), ('4', 'Pert Depo')], default='1', max_length=10, null=True, verbose_name='Lokasyon')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('engine_mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.mark', verbose_name='Marka')),
                ('engine_power', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.power', verbose_name='Motor Gücü')),
            ],
            options={
                'ordering': ('engine_power__engine_power',),
            },
        ),
    ]
