# Generated by Django 5.2.9 on 2025-12-09 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='location',
            field=models.CharField(choices=[('1', 'Kuyuda'), ('2', 'Tamir Depo'), ('3', '2.El Depo'), ('4', 'Pert Depo'), ('5', 'Sıfır Depo')], default='1', max_length=10, null=True, verbose_name='Lokasyon'),
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_type', models.CharField(max_length=25, verbose_name='Tipi')),
                ('pump_breed', models.CharField(choices=[('1', 'KROM'), ('2', 'NORİL'), ('3', 'DÖKÜM'), ('4', 'PİK'), ('5', '-')], max_length=5, verbose_name='Cinsi')),
                ('number_stages', models.PositiveIntegerField(default=0, verbose_name='Kademe Sayısı')),
                ('location', models.CharField(choices=[('1', 'Kuyuda'), ('2', 'Tamir Depo'), ('3', '2.El Depo'), ('4', 'Pert Depo'), ('5', 'Sıfır Depo')], default='1', max_length=10, null=True, verbose_name='Lokasyon')),
                ('comment', models.TextField(blank=True, verbose_name='Açıklama')),
                ('pump_mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.mark', verbose_name='Pompa Markası')),
            ],
            options={
                'ordering': ('pump_type',),
                'constraints': [models.UniqueConstraint(fields=('pump_type', 'pump_breed', 'number_stages', 'pump_mark'), name='unique_pump_combination')],
            },
        ),
    ]
