# Generated by Django 5.2.9 on 2025-12-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_alter_engine_location_pump'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Miktar'),
        ),
    ]
