# Generated by Django 5.2.9 on 2025-12-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_remove_pump_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='quantity',
        ),
    ]
