# Generated by Django 5.2.9 on 2025-12-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_remove_pump_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_number', models.CharField(max_length=100, unique=True, verbose_name='Kuyu Numarası')),
                ('district', models.CharField(choices=[('akçakale', 'AKÇAKALE'), ('eyyübiye', 'EYYÜBİYE'), ('birecik', 'BİRECİK'), ('bozova', 'BOZOVA'), ('ceylanpınar', 'CEYLANPINAR'), ('halfeti', 'HALFETİ'), ('haliliye', 'HALİLİYE'), ('harran', 'HARRAN'), ('hilvan', 'HİLVAN'), ('karaköprü', 'KARAKÖPRÜ'), ('siverek', 'SİVEREK'), ('suruç', 'SURUÇ'), ('viranşehir', 'VİRANŞEHİR')], max_length=50, verbose_name='İlçe')),
                ('address', models.CharField(max_length=50, verbose_name='Adres')),
                ('disassembly_depth', models.PositiveIntegerField(verbose_name='Demontaj Derinliği')),
                ('mounting_depth', models.PositiveIntegerField(verbose_name='Montaj Derinliği')),
                ('tank_info', models.CharField(max_length=50, verbose_name='Depo Bilgisi')),
                ('pipe_type', models.CharField(max_length=50, verbose_name='Boru Tipi')),
                ('cable', models.CharField(max_length=15, verbose_name='Kablo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.CharField(blank=True, max_length=50, null=True, verbose_name='Debi')),
                ('comment', models.TextField(blank=True, verbose_name='Açıklama')),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.engine', verbose_name='Motor')),
                ('pump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.pump', verbose_name='Pompa')),
            ],
            options={
                'ordering': ('well_number',),
            },
        ),
    ]
