# Generated by Django 5.2.9 on 2025-12-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0006_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='storeno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Depono'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('engine',), name='unique_engine_for_inventory'),
        ),
    ]
