# Generated by Django 5.2.9 on 2025-12-22 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0007_engine_storeno_inventory_unique_engine_for_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seconhand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_identifier', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.engine')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.pump')),
            ],
        ),
    ]
