# Generated by Django 5.2.9 on 2025-12-22 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0008_seconhand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seconhand',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.engine'),
        ),
        migrations.AlterField(
            model_name='seconhand',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.pump'),
        ),
        migrations.AlterField(
            model_name='seconhand',
            name='row_identifier',
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
    ]
