# Generated by Django 5.2.9 on 2025-12-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0009_alter_seconhand_engine_alter_seconhand_pump_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seconhand',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
