# Generated by Django 5.2.9 on 2025-12-27 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0013_remove_repair_row_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='location',
            field=models.CharField(choices=[('1', 'Kuyuda'), ('2', 'Tamir Depo'), ('3', '2.El Depo'), ('4', 'Pert Depo'), ('5', 'Sıfır Depo')], default='5', max_length=10, null=True, verbose_name='Lokasyon'),
        ),
        migrations.CreateModel(
            name='Unusable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.engine')),
                ('pump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.pump')),
                ('well_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.inventory')),
            ],
        ),
    ]
