# Generated by Django 5.2.9 on 2025-12-28 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0014_alter_engine_location_unusable'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWarehousePump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('pump', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouses.pump')),
            ],
        ),
    ]
