# Generated by Django 5.2.9 on 2025-12-28 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0015_newwarehousepump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwarehousepump',
            name='pump',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.pump'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_plug', models.CharField(max_length=10, unique=True, verbose_name='Çıkış Fişi')),
                ('entrance_plug', models.CharField(max_length=10, unique=True, verbose_name='Giriş Fişi')),
                ('outlet_plug_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Çıkış Fişi Tarihi')),
                ('entrance_plug_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Giriş Fişi Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('passive', 'Pasif')], default='active', max_length=7, verbose_name='Durum')),
                ('disassembled_engine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='disassembled_engine_orders', to='warehouses.engine', verbose_name='Demontaj Edilen Motor')),
                ('disassembled_pump', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='disassembled_pump_orders', to='warehouses.pump', verbose_name='Demontaj Edilen Pompa')),
                ('inventory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.inventory', verbose_name='Kuyu Bilgisi')),
                ('mounted_engine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mounted_engine_orders', to='warehouses.engine', verbose_name='Montaj Edilen Motor')),
                ('mounted_pump', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mounted_pump_orders', to='warehouses.pump', verbose_name='Montaj Edilen Pompa')),
            ],
        ),
    ]
