# Generated by Django 5.2.9 on 2025-12-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0016_alter_newwarehousepump_pump_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='disassembled_engine',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.engine', verbose_name='Demontaj Edilen Motor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='disassembled_pump',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.pump', verbose_name='Demontaj Edilen Pompa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entrance_plug',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Giriş Fişi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='outlet_plug',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Çıkış Fişi'),
        ),
    ]
