# Generated by Django 5.2.9 on 2025-12-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0017_alter_order_disassembled_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mounted_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mounted_engine_orders', to='warehouses.engine', verbose_name='Montaj Edilen Motor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mounted_pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mounted_pump_orders', to='warehouses.pump', verbose_name='Montaj Edilen Pompa'),
        ),
    ]
