# Generated by Django 6.0 on 2025-12-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0018_alter_order_mounted_engine_alter_order_mounted_pump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='disassembled_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.engine', verbose_name='Demontaj Edilen Motor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='disassembled_pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.pump', verbose_name='Demontaj Edilen Pompa'),
        ),
    ]
