# Generated by Django 5.2.9 on 2025-12-31 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0019_alter_order_disassembled_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='engine_type',
            field=models.CharField(choices=[('1', '3′'), ('2', '4′'), ('3', '5′'), ('4', '6′'), ('5', '7′'), ('6', '8′'), ('7', '9′'), ('8', '10′'), ('9', '11′'), ('10', 'ASENKRON'), ('11', '-')], max_length=4, verbose_name='Motor Tipi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entrance_plug_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Giriş Fişi Tarihi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='outlet_plug_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Çıkış Fişi Tarihi'),
        ),
    ]
