# Generated by Django 5.2.9 on 2025-12-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0020_alter_engine_engine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='engine_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Motor Durumu'),
        ),
        migrations.AddField(
            model_name='order',
            name='pump_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pompa Durumu'),
        ),
    ]
