# Generated by Django 5.2.9 on 2026-01-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0021_order_engine_info_order_pump_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
