# Generated by Django 6.0 on 2026-01-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0022_order_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hydrophore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(verbose_name='Hidrofor Seri Numarası')),
                ('motor_power', models.FloatField(verbose_name='Motor Gücü')),
                ('motor_brand', models.CharField(max_length=100, verbose_name='Motor Markası')),
                ('pump_type', models.CharField(max_length=100, verbose_name='Pompa Tipi')),
                ('pump_brand', models.CharField(max_length=100, verbose_name='Pompa Markası')),
                ('location', models.CharField(choices=[('Ankara', 'Ankara'), ('Istanbul', 'İstanbul'), ('Izmir', 'İzmir'), ('Bursa', 'Bursa')], max_length=50, verbose_name='Lokasyon')),
                ('district', models.CharField(blank=True, choices=[('Neighborhood 1', 'Mahalle 1'), ('Neighborhood 2', 'Mahalle 2'), ('Neighborhood 3', 'Mahalle 3')], max_length=100, null=True, verbose_name='İlçe')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Mahalle')),
            ],
            options={
                'verbose_name': 'Hidrofor',
                'verbose_name_plural': 'Hidroforlar',
            },
        ),
        migrations.AlterField(
            model_name='seconhand',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.engine'),
        ),
        migrations.AlterField(
            model_name='seconhand',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.pump'),
        ),
    ]
