# Generated by Django 5.2.9 on 2026-01-10 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0023_hydrophore_alter_seconhand_engine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hydrophore',
        ),
        migrations.AlterField(
            model_name='order',
            name='entrance_plug',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Atölyeden Giden Fiş'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entrance_plug_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Atölyeden Giden Fiş Tarihi'),
        ),
    ]
