# Generated by Django 5.2.9 on 2026-01-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0024_delete_hydrophore_alter_order_entrance_plug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='disassembled_engine',
        ),
        migrations.RemoveField(
            model_name='order',
            name='disassembled_pump',
        ),
        migrations.RemoveField(
            model_name='order',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mounted_engine',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mounted_pump',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='pump',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='well_number',
        ),
        migrations.RemoveField(
            model_name='seconhand',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='seconhand',
            name='pump',
        ),
        migrations.RemoveField(
            model_name='unusable',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='unusable',
            name='pump',
        ),
        migrations.RemoveField(
            model_name='unusable',
            name='well_number',
        ),
        migrations.AlterModelOptions(
            name='engine',
            options={'ordering': ('engine_power__engine_power',), 'verbose_name': 'Motor', 'verbose_name_plural': 'Motorlar'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('well_number',), 'verbose_name': 'Kuyu', 'verbose_name_plural': 'Kuyular'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Markalar'},
        ),
        migrations.AlterModelOptions(
            name='power',
            options={'verbose_name': 'Güç', 'verbose_name_plural': 'Güçler'},
        ),
        migrations.AlterModelOptions(
            name='pump',
            options={'ordering': ('pump_type',), 'verbose_name': 'Pompa', 'verbose_name_plural': 'Pompalar'},
        ),
        migrations.AlterField(
            model_name='engine',
            name='location',
            field=models.CharField(choices=[('1', 'Kuyuda'), ('2', 'Tamir Depo'), ('3', '2.El Depo'), ('4', 'Pert Depo'), ('5', 'Sıfır Depo'), ('6', 'Mütahit Depo')], default='5', max_length=10, null=True, verbose_name='Lokasyon'),
        ),
        migrations.DeleteModel(
            name='NewWarehousePump',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Repair',
        ),
        migrations.DeleteModel(
            name='Seconhand',
        ),
        migrations.DeleteModel(
            name='Unusable',
        ),
    ]
