# Generated by Django 5.2.9 on 2026-01-20 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0026_newwarehousepump_outboundworkorder_repair_seconhand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopExitSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('slip_no', models.CharField(max_length=100, verbose_name='Fiş No')),
                ('well_no', models.CharField(max_length=100, verbose_name='Kuyu No')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('address', models.CharField(max_length=100, verbose_name='Adres')),
                ('motor_type', models.CharField(max_length=100, verbose_name='Motor Tipi')),
                ('hydrofor_no', models.CharField(max_length=100, verbose_name='Hidrofor No')),
                ('brand', models.CharField(max_length=100, verbose_name='Markası')),
                ('power', models.CharField(max_length=100, verbose_name='Gücü')),
                ('pump_type', models.CharField(max_length=100, verbose_name='Pompa Tipi')),
                ('pump_brand', models.CharField(max_length=100, verbose_name='Pompa Markası')),
                ('submersible', models.CharField(max_length=100, verbose_name='Dalgıç')),
                ('motor', models.CharField(max_length=100, verbose_name='Motor')),
                ('pump', models.CharField(max_length=100, verbose_name='Pompa')),
                ('hydrofor', models.CharField(max_length=100, verbose_name='Hidrofor')),
                ('main_pipe', models.CharField(max_length=100, verbose_name='Ö.Boru')),
                ('secondary_pipe', models.CharField(max_length=100, verbose_name='K.Boru')),
                ('maintenance_status', models.CharField(max_length=100, verbose_name='Bakım Durumu')),
                ('overall_status', models.CharField(max_length=100, verbose_name='Genel Durum')),
            ],
            options={
                'verbose_name': 'Tüm Atölye Çıkış Fişi',
                'verbose_name_plural': 'Tüm Atölye Çıkış Fişleri',
                'ordering': ('date',),
            },
        ),
        migrations.RemoveField(
            model_name='workshopexit',
            name='outbound_work_order',
        ),
        migrations.RemoveField(
            model_name='repairreturn',
            name='workshop_exit',
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'verbose_name': 'Tamir Depo', 'verbose_name_plural': 'Tamir Depolar'},
        ),
        migrations.AlterModelOptions(
            name='seconhand',
            options={'verbose_name': '2.El Depo', 'verbose_name_plural': '2.El Depolar'},
        ),
        migrations.AlterModelOptions(
            name='unusable',
            options={'verbose_name': 'Pert Depo', 'verbose_name_plural': 'Pert Depolar'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_plug', models.CharField(max_length=10, null=True, unique=True, verbose_name='Çıkış Fişi')),
                ('entrance_plug', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Atölyeden Giden Fiş')),
                ('outlet_plug_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Çıkış Fişi Tarihi')),
                ('entrance_plug_date', models.DateField(blank=True, null=True, verbose_name='Atölyeden Giden Fiş Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('passive', 'Pasif')], default='active', max_length=7, verbose_name='Durum')),
                ('engine_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='Motor Durumu')),
                ('pump_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pompa Durumu')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('disassembled_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.engine', verbose_name='Demontaj Edilen Motor')),
                ('disassembled_pump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.pump', verbose_name='Demontaj Edilen Pompa')),
                ('inventory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.inventory', verbose_name='Kuyu Bilgisi')),
                ('mounted_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mounted_engine_orders', to='warehouses.engine', verbose_name='Montaj Edilen Motor')),
                ('mounted_pump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mounted_pump_orders', to='warehouses.pump', verbose_name='Montaj Edilen Pompa')),
            ],
            options={
                'verbose_name': 'İş Emri',
                'verbose_name_plural': 'İş Emirleri',
            },
        ),
        migrations.DeleteModel(
            name='OutboundWorkOrder',
        ),
        migrations.DeleteModel(
            name='RepairReturn',
        ),
        migrations.DeleteModel(
            name='WorkshopExit',
        ),
    ]
