# Generated by Django 5.2.9 on 2026-01-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0027_workshopexitslip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopexitslip',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Markası'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='hydrofor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hidrofor'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='hydrofor_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hidrofor No'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='main_pipe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ö.Boru'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='maintenance_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bakım Durumu'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='motor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motor'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='motor_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motor Tipi'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='overall_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Genel Durum'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='power',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gücü'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='pump',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pompa'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='pump_brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pompa Markası'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='pump_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pompa Tipi'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='secondary_pipe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='K.Boru'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='submersible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dalgıç'),
        ),
        migrations.AlterField(
            model_name='workshopexitslip',
            name='well_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kuyu No'),
        ),
    ]
