# Generated by Django 5.2.9 on 2026-01-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0028_alter_workshopexitslip_address_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pump',
            name='unique_pump_combination',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='number_stages',
        ),
        migrations.AlterField(
            model_name='pump',
            name='pump_type',
            field=models.CharField(max_length=50, verbose_name='Tipi'),
        ),
        migrations.AddConstraint(
            model_name='pump',
            constraint=models.UniqueConstraint(fields=('pump_type', 'pump_breed', 'pump_mark'), name='unique_pump_combination'),
        ),
    ]
