# Generated by Django 5.2.9 on 2026-01-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0029_remove_pump_unique_pump_combination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshopexitslip',
            options={'ordering': ('-date', '-slip_no'), 'verbose_name': 'Tüm Atölye Çıkış Fişi', 'verbose_name_plural': 'Tüm Atölye Çıkış Fişleri'},
        ),
        migrations.AlterField(
            model_name='order',
            name='inventory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.inventory', verbose_name='Kuyu Bilgisi'),
        ),
    ]
