# Generated by Django 6.0 on 2026-01-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0029_remove_pump_unique_pump_combination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshopexitslip',
            options={'ordering': ('-date', '-slip_no'), 'verbose_name': 'Tüm Atölye Çıkış Fişi', 'verbose_name_plural': 'Tüm Atölye Çıkış Fişleri'},
        ),
    ]
