# Generated by Django 5.2.9 on 2026-01-29 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0030_alter_workshopexitslip_options_alter_order_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwarehousepump',
            name='pump',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.pump'),
        ),
        migrations.AlterField(
            model_name='order',
            name='disassembled_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.engine', verbose_name='Demontaj Edilen Motor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='disassembled_pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.pump', verbose_name='Demontaj Edilen Pompa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mounted_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mounted_engine_orders', to='warehouses.engine', verbose_name='Montaj Edilen Motor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mounted_pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mounted_pump_orders', to='warehouses.pump', verbose_name='Montaj Edilen Pompa'),
        ),
    ]
