# Generated by Django 5.2.9 on 2026-01-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0031_alter_newwarehousepump_pump_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.engine', verbose_name='Motor'),
        ),
    ]
