# Generated by Django 5.2.9 on 2026-02-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0034_alter_repair_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['outlet_plug_date'], 'verbose_name': 'İş Emri', 'verbose_name_plural': 'İş Emirleri'},
        ),
    ]
