# Generated by Django 5.2.9 on 2026-02-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0030_alter_workshopexitslip_options'),
        ('warehouses', '0035_alter_order_options'),
    ]

    operations = [
    ]
