# Generated by Django 5.2.9 on 2026-02-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0036_merge_20260210_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('passive', 'Pasif')], default='active', max_length=7, verbose_name='Durum'),
        ),
    ]
