# Generated by Django 5.2.9 on 2026-02-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0037_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='disassembly_plug',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Demontaj Fişi'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_order_plug',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='İş Emri Fişi'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.engine', verbose_name='Motor'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.pump', verbose_name='Pompa'),
        ),
    ]
