# Generated by Django 5.2.9 on 2026-02-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0038_order_disassembly_plug_order_work_order_plug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='situation',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='İş Emri Durumu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='disassembly_plug',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Demontaj Fişi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.inventory', verbose_name='Kuyu Bilgisi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='outlet_plug',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Çıkış Fişi'),
        ),
    ]
