# Generated by Django 5.2.9 on 2026-02-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0039_order_situation_alter_order_disassembly_plug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='outlet_plug_date',
            field=models.DateField(blank=True, null=True, verbose_name='Çıkış Fişi Tarihi'),
        ),
    ]
