# Generated by Django 5.2.9 on 2026-02-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0040_order_created_at_alter_order_outlet_plug_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operation_engine',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İşlem Türü'),
        ),
    ]
