# Generated by Django 5.2.9 on 2026-02-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0042_alter_order_disassembly_plug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='disassembly_plug',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Demontaj Fişi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entrance_plug',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Atölyeden Giden Fiş'),
        ),
        migrations.AlterField(
            model_name='order',
            name='outlet_plug',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Çıkış Fişi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_order_plug',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='İş Emri Fişi'),
        ),
    ]
