# Generated by Django 5.2.9 on 2026-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0043_alter_order_disassembly_plug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('1', 'Demontaj Bekliyor'), ('2', 'Demontaj Yapıldı'), ('3', 'Kurtarıcıda'), ('4', 'Atölyede'), ('5', 'Tamire Gönderildi'), ('6', 'Montaj Bekliyor'), ('7', 'Montaj Yapıldı'), ('8', 'Boy ekleme'), ('9', 'Kuyu İptal')], max_length=15, null=True, verbose_name='İşlem Türü'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operation_engine',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dalgıç işlem Türü'),
        ),
        migrations.AlterField(
            model_name='order',
            name='situation',
            field=models.CharField(blank=True, choices=[('installation', 'Yerinde Montaj'), ('dismantling', 'Demontaj'), ('length_extension', 'Boy Ekleme'), ('well_cancellation', 'Kuyu İptal')], max_length=20, null=True, verbose_name='İş Emri Durumu'),
        ),
    ]
