# Generated by Django 5.2.9 on 2026-02-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0044_order_operation_type_alter_order_operation_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='operation_engine',
            field=models.CharField(blank=True, choices=[('engine', 'Motor'), ('pump', 'Pompa'), ('engine_pump', 'Motor + Pompa')], max_length=50, null=True, verbose_name='Dalgıç işlem Türü'),
        ),
    ]
