# Generated by Django 5.2.9 on 2026-02-16 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0045_alter_order_operation_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('1', 'Demontaj Bekliyor'), ('2', 'Kurtarıcıda'), ('3', 'Atölyede'), ('4', 'Tamire Gönderildi'), ('5', 'Montaj Bekliyor'), ('6', 'Montaj Yapıldı'), ('7', 'Boy Ekleme Bekliyor'), ('8', 'Kuyu İptal')], max_length=15, null=True, verbose_name='İşlem Türü'),
        ),
        migrations.AlterField(
            model_name='order',
            name='outlet_plug_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Çıkış Fişi Tarihi'),
        ),
    ]
