# Generated by Django 5.2.9 on 2026-02-16 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0046_alter_order_operation_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-work_order_plug'], 'verbose_name': 'İş Emri', 'verbose_name_plural': 'İş Emirleri'},
        ),
        migrations.AlterField(
            model_name='order',
            name='entrance_plug_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Atölyeden Giden Fiş Tarihi'),
        ),
    ]
