# Generated by Django 5.2.9 on 2026-02-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0047_alter_order_options_alter_order_entrance_plug_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assembly_plug',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Montaj Fişi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('1', 'Demontaj Bekliyor'), ('2', 'Kurtarıcıda'), ('3', 'Atölyede'), ('4', 'Tamire Gönderildi'), ('5', 'Çıkış Fişi Oluştur'), ('6', 'Montaj Bekliyor'), ('7', 'Montaj Yapıldı'), ('8', 'Boy Ekleme Bekliyor'), ('9', 'Kuyu İptal'), ('10', 'Kapandı')], max_length=15, null=True, verbose_name='İşlem Türü'),
        ),
    ]
