# Generated by Django 5.2.9 on 2026-02-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0048_order_assembly_plug_alter_order_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Boru uzunluğu'),
        ),
    ]
