# Generated by Django 5.2.9 on 2026-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0049_order_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopexitslip',
            name='modal_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İd'),
        ),
    ]
