# Generated by Django 5.2.9 on 2026-03-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0050_workshopexitslip_modal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='situation',
            field=models.CharField(blank=True, choices=[('installation', 'Yerinde Montaj'), ('dismantling', 'Demontaj'), ('length_extension', 'Boy Ekleme'), ('well_cancellation', 'Kuyu İptal'), ('new_well', 'Yeni Kuyu')], max_length=20, null=True, verbose_name='İş Emri Durumu'),
        ),
    ]
