# Generated by Django 5.2.9 on 2026-03-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0051_alter_order_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='storeno',
        ),
    ]
