# Generated by Django 5.2.9 on 2026-03-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0052_remove_engine_storeno'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Çıkış Fişi Tarihi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.inventory', verbose_name='Kuyu Bilgisi')),
            ],
            options={
                'verbose_name': 'Borç Durumu',
                'verbose_name_plural': 'Bor. Durumları',
                'ordering': ['date'],
            },
        ),
    ]
