# Generated by Django 6.0 on 2026-03-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0053_debtsituation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtsituation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Tarih'),
        ),
    ]
