# Generated by Django 6.0 on 2026-04-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0054_alter_debtsituation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtsituation',
            options={'ordering': ['-date'], 'verbose_name': 'Borç Durumu', 'verbose_name_plural': 'Bor. Durumları'},
        ),
    ]
